workspace:
  base: /go
  path: src/github.com/midorigreen/drone-sample

pipeline:
  build:
    image: golang:1.10.2
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - ls
      - dep ensure
      - go build
      - go test
