// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	context "context"
)

// Injectors from inject.go:

func setUp(ctx context.Context, n fooName, z string) (Foo, error) {
	foo := ProviderFoo(n)
	return foo, nil
}
